### ISSUE TITLE
Ability to stop polpetta instance from command line

### ISSUE THREAD

**Issue by JamesMGreene** [WebReflection/polpetta#4]
Wanted: Ability to stop polpetta instance from command line, with the same basic input combos as the command to start them. For example:
- node polpetta --stop
- node polpetta --stop ./
- node polpetta --stop 8080
- node polpetta --stop ./ 8080

Not 100% sure what the last one would do:
1. Stop the polpetta instance only if it matched both inputs
2. Stop the polpetta instances (possibly 2+) that match each individual input

Please consider it. Thanks!

**Comment by WebReflection** [comment]
the port is chosen runtime ... consider two polpetta on same folder but with different port ( e.g. for different behavior )
what should --stop same_folder/ do in this case if no port has been specified ?
Also, polpetta takes through node the current prompt as process id and is not storing anywhere the current status.
Since your prompt/cmd won't return until polpetta is running, why do you need such feature?
Last, but not least, have you ever seen something like this in a node.js script? If yeas, please tell me where 'cause maybe it's easy and it makes sense. So far, I have no idea who would use such hack but I might be wrong.

**Comment by JamesMGreene** [comment]
1. I would expect Polpetta to stop all of the running instances (ports) for that folder.
2. I would be executing Polpetta in the background (so the rest of my build script can continue running, but making HTTP requests for the Polpetta-served files). In the build system being used (Ant), there is no way for me to recover a console application run in the background [on Windows].  As such, I need a separate mechanism like this to force an abort of the Polpetta instance started earlier.
3. Honestly, I haven't used/seen enough of the node.js world yet, so I'm definitely not the best person to answer this.

As supplemental information, I do know that the servedir devs (@kitcambridge, in particular) _are_ legitimately interested in supporting this and looking into it. Kit [mentioned](https://twitter.com/kitcambridge/status/230140444271583232) that he believes they can get it to run in the background by unlinking the socket. I filed a related issue for them: remy/servedir#16

**Comment by WebReflection** [comment]
I might spawn the process and detach it after initial checks ( after the server is started ), however this will require some log making polpetta unusable in a read-only environment.
Right now I am doing some deep clean up to make the code more readable and easier to maintain/improve.
Once the whole logic is in place and tested, together with complete .htaccess features, this might be the next thing to do.
As summary, it's a matter of priorities, also I believe this should not be part of polpetta itself, rather part of a generic node child processes manager so probably a project a part.

**Comment by JamesMGreene** [comment]
It seems the `servedir` folks came to the same general conclusion after their analysis: remy/servedir#16

**Comment by WebReflection** [comment]
I have created _chef_, which is basically what you asked. `chef start ~/folder 2000` and `chef stop ~/folder 2000`
If you don't specify the port any `~/folder` registered with a polpetta instance will be stopped.
If you don't specify the port while starting, a new port is creted automatically.
Missing part is just `chef stop` to stop all polpetta instances, coming soon I guess :)

**Comment by WebReflection** [comment]
James, _chef_ now supports serverdir too and it works like this:

`chef start|stop [polpetta|serverdir] [path|process.cwd()] [port|*find one automatically*]`
- if you don't specify the program, polpetta is the default
- if you don't specify the path, current folder is the default
- if you don't specify the port, one is discovered runtime

If you `chef stop polpetta` all instances will be killed, same is for `chef stop serverdir`, otherwise you can stop path and port or all instances in the same path.

I hope this is enough, please close this _issue_ when you test it, thanks.

**Comment by WebReflection** [comment]
as follow up, polpetta now uses [webf](https://github.com/WebReflection/webf) so feel free to open issues there if you still need something from the tool, thanks. I close this since it is not related anymore
