### ISSUE TITLE
file watching (njs files on windows)

### ISSUE THREAD

**Issue by szkrd** [WebReflection/polpetta#6]
Njs files are not reparsed automatically, only on polpetta restart, which is cumbersome. I tried installing chef (??), but I had to realize that npm chef is something totally different.

If there's a proper solution for file watching (like adding a parameter to enable polling) on Windows, please update the md file. Thanks!

**Comment by WebReflection** [comment]
this is not a bug since .njs files are loaded through require() and require() does cache and it does in this case for performances reasons. Not sure there is an easy way to invalidate required files each time for an easier development but I'll try to figure out how. If not possible, I have to assume during development it's OK to evaluate runtime or kill and re-run polpetta per each request.

Chef is now [webf](https://github.com/WebReflection/webf) but the goal is different, I know chef was taken for something that does not make sense :dancer: that's why I had to rename the project :(

**Comment by szkrd** [comment]
Thanks for the response, I didn't know about the require - it may be a good idea to mention it in the readme.

While fooling around with nginx and apache I had the weird idea of firing up polpetta for a local server, not just for testing, but to have it run in the background, since it would be very easy to work with (also thought about nodewebkit, which is not a server per se), but I'm not sure if I want to create a restarter tool (shortcute? ahk script? jedit on save actionhook?). Nevertheless it's still useful the way it is and thank you for your efforts.

**Comment by risseraka** [comment]
Would http://nodejs.org/docs/latest/api/globals.html#globals_require_cache fix the "problem"?

**Comment by WebReflection** [comment]
awesome, I didn't know about that and Yes, patched already, feel free to update and use `FORCE_NJS_RELOAD = true` flag in the main file. By default is still `false` 'cause tests are obviously failing without cache but not because polpetta is broken so ... until I have time to fix tests or change them in a better way that's how it is, I hope it's OK :-)

Thanks!

**Comment by risseraka** [comment]
Was working on a patch, you were a bit fast!
A bit too fast, maybe. ; )

My idea of the feature was more like:

```
var module = require(path);
if (!watchedFiles[path]) {
    watchedFiles[path] = true;
    fs.watch(path, function () {
        console.log('reloading:', path);
        delete require.cache[path];
    });
}
```
- require the file the first time it's accesssed (nothing to change here);
- watch the file (keep a tracked files index or something somewhere to prevent watching multiple times);
- delete cache if file changed.

fs.watch has caveats though, as I've gathered, nfs issues for example.

**Comment by WebReflection** [comment]
I would not go for that direction for the simple reason that watch is not working on windows, at least didn't work when I have created webf (ex chef) but yes, once watch is stable in windows too I'll use it. Right now this is good enough, imho, there are more things I would like to focus on such request range and partial bytes as response so it can be used for video stream too and loop properly behaving like a web server ;-)

**Comment by risseraka** [comment]
Strange, it works perfectly fine in my Windows environment.
Well, I might shoot a pull request with tests someday, that'll alleviate you some time to focus on those other things.
Cheers!

**Comment by WebReflection** [comment]
feel free to, I am testing Windows 7 Pro in Atom based Netbook (real slow shit) and watch ain't working ... I might try again but I think it was also in the documentation itself
